version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

  scraper:
    container_name: navigate_scraper
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    command: ["python", "main.py"]

volumes:
  db_data:
